export const texts = [
  'The sky above the port was the color of television, tuned to a dead channel.',
  'In Neuromancer, published 30 years ago this month, Gibson popularised the  idea of cyberspace: a "consensual hallucination"  created by millions of connected computers. This network can be "jacked" into, while in the real world characters flit from Tokyo to the Sprawl, an urban agglomeration running down the east coast of the US. Gritty urban clinics carry out horrendous sounding plastic surgery. A junkie-hacker, Case, is coaxed into hacking the system of a major corporation. What once seemed impossibly futuristic is now eerily familiar.',
  '"No girl? Nothing? Only biz, friend artiste? Dedication to commerce?" The bartender\'s small brown eyes were nested deep in wrinkled flesh. "I think I liked you better, with her. You laughed more. Now, some night, you get maybe too artistic, you wind up in the clinic tanks, spare parts."',
  'His total assets were quickly converted to New Yen, a fat sheaf of the old paper currency that circulated endlessly through the closed circuit of the world\'s black markets like the seashells of the Trobriand islanders. It was difficult to transact legitimate business with cash in the Sprawl; in Japan, it was already illegal.',
  'In Japan, he\'d known with a clenched and absolute certainty, he\'d find his cure. In Chiba. Either in a registered clinic or in the shadow land of black medicine. Synonymous with implants, nerve-splicing, and micro bionics, Chiba was a magnet for the Sprawl\'s techno-criminal subcultures.',
  'Two blocks west of the Chat, in a teashop called the Jarre de The, Case washed down the night\'s first pill with a double espresso. It was a flat pink octagon, a potent species of Brazilian dex he bought from one of Zone\'s girls. The Jarre was walled with mirrors, each panel framed in red neon.',
  'Their night together stretching into a morning, into tickets at the hover port and his first trip across the Bay. The rain kept up, falling along Harajuku, beading on her plastic jacket, the children of Tokyo trooping past the famous boutiques in white loafers and cling wrap capes, until she\'d stood with him in the midnight clatter of a pachinko parlor and held his hand like a child.',
  '"I\'ll see you, Linda," he said, getting up.',
  'The sarariman had been Japanese, but the Ninsei crowd was a gaijin crowd. Groups of sailors up from the port, tense solitary tourists hunting pleasures no guidebook listed, Sprawl heavies showing off grafts and implants, and a dozen distinct species of hustler, all swarming the street in an intricate dance of desire and commerce.'
];